apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-validator-gke
spec:
  replicas: 110
  selector:
    matchLabels:
      app: gtfs-validator
  template:
    metadata:
      labels:
        app: gtfs-validator
    spec:
      containers:
        - name: gtfs-validator-container
          image: us-east1-docker.pkg.dev/{{PROJECT_ID}}/gtfs-validator-repo/gtfs-validator-snapshot-cluster:{{TAG}}}
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
