name: Rule acceptance tests

on:
  push:
    branches: [ master, ci/use-github-matrix ]
    paths-ignore:
      - '**.md'
jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: get url list
        run: |
          DATASETS=$(curl https://gtfs-validator.free.beeceptor.com/urls)
          echo $DATASETS
          echo "::set-output name=matrix::$DATASETS"
  get-latest-changes-report:
    needs: [ fetch-urls ]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.fetch-urls.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.data }}
