name: Rule acceptance tests

on:
  push:
    branches: [ master, ci/acceptance-tests ]
    paths-ignore:
      - '**.md'
jobs:
  setup-cloud-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Create repository
        run: |
          gcloud artifacts repositories create gtfs-validator-repo \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --repository-format=docker \
          --location=us-east1 \
          --description="Docker repository"
      - name: Build and push snapshot image on Google Container Registry
        run: |
          gcloud builds submit --tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gtfs-validator-repo/gtfs-validator-snapshot-gke .
