name: Rule acceptance tests

on:
  push:
    branches: [ master, ci/acceptance-tests ]
    paths-ignore:
      - '**.md'
jobs:
  setup-cloud-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
