name: Rule acceptance tests

on:
  push:
    branches: [ master, ci/use-github-matrix ]
    paths-ignore:
      - '**.md'
jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Set URL matrix
        id: set-matrix
        run: |
          DATASETS=$(curl https://gtfs-validator.free.beeceptor.com/test)
          echo $DATASETS
          echo "::set-output name=matrix::$DATASETS"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  get-latest-changes-report:
    needs: fetch-urls
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.fetch-urls.outputs.matrix) }}
    steps:
      - name: display matrix data
        run: |
          echo ${{ matrix.data}}
